public enum EventTypeEnum
{
    None,
    BALL_BALL,
    BALL_LINEAR_CUSHION,
    BALL_CIRCULAR_CUSHION,
    BALL_POCKET,
    STICK_BALL,
    SPINNING_STATIONARY,
    ROLLING_STATIONARY,
    ROLLING_SPINNIG,
    SLIDING_ROLLING
}
